// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE61JXAjAo4hIX8IR1jJVdx8CTq1S3r9g',
    appId: '1:344927788966:web:3bd0b96b05820284beb967',
    messagingSenderId: '344927788966',
    projectId: 'nalift',
    authDomain: 'nalift.firebaseapp.com',
    databaseURL:
        'https://nalift-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nalift.firebasestorage.app',
    measurementId: 'G-5WPQ3FMW0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJYcuWXt_1IAp7pYkeYdzjpYeQ9AKYT0',
    appId: '1:344927788966:android:efab7ea05452b982beb967',
    messagingSenderId: '344927788966',
    projectId: 'nalift',
    databaseURL:
        'https://nalift-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nalift.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6zRlyr18F52EF9W8BClWwGIouU77gRb8',
    appId: '1:344927788966:ios:83304674b8077056beb967',
    messagingSenderId: '344927788966',
    projectId: 'nalift',
    databaseURL:
        'https://nalift-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nalift.firebasestorage.app',
    iosBundleId: 'com.kevin.nalift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6zRlyr18F52EF9W8BClWwGIouU77gRb8',
    appId: '1:344927788966:ios:83304674b8077056beb967',
    messagingSenderId: '344927788966',
    projectId: 'nalift',
    databaseURL:
        'https://nalift-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nalift.firebasestorage.app',
    iosBundleId: 'com.kevin.nalift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE61JXAjAo4hIX8IR1jJVdx8CTq1S3r9g',
    appId: '1:344927788966:web:f91ec9cd997c1e2dbeb967',
    messagingSenderId: '344927788966',
    projectId: 'nalift',
    authDomain: 'nalift.firebaseapp.com',
    databaseURL:
        'https://nalift-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nalift.firebasestorage.app',
    measurementId: 'G-8D4WYDQMFZ',
  );
}
